os: linux
dist: focal
language: python
addons: 
  - sbom:
      on:
        branch: sbom_one_fix
        pr: true
      run_phase: before_script
      output_format: spdx-json
      output-dir: 'python'
  - mariadb
script:
  - python hello_world.py
