jobs:
  include:
    - name: Windows Node JS
      os: windows
      language: node_js
      addons:
        sbom:
          on:
            branch: main
            condition: $OS = linux
          run_phase: after_failure
          output_format: cyclonedx-xml
        mariadb: '10.0'
      script:
        - cd node
#         - npm install
        - node hello_world.js
