jobs:
  include:
    - name: Linux Focal Python
      os: linux
      dist: focal
      language: python
      addons:
        sbom:
          on:
            branch: main
            pr: true
          run_phase: after_failure
          output_format: cyclonedx-xml
        mariadb: '10.0'
      script:
        - python hello_world.py
        - cd python
        - pip install -r requirements.txt
    - name: Linux Jammy Python
      os: linux
      dist: jammy
      language: python
      python:
        - "3.9"
      addons:
        sbom:
          on:
            branch: main
            pr: true
          run_phase: after_failure
          output_format: cyclonedx-json
        mariadb: '10.0'
      script:
        - python hello_world.py
        - cd python
        - pip install -r requirements.txt
    - name: Linux Xenial Python
      os: linux
      dist: xenial
      language: python
      addons:
        sbom:
          on:
            branch: main
            pr: true
          run_phase: after_failure
          output_format: spdx-json
        mariadb: '10.0'
      script:
        - python hello_world.py
        - cd python
        - pip install -r requirements.txt
    - name: Linux Bionic Python
      os: linux
      dist: bionic
      language: python
      addons:
        sbom:
          on:
            branch: main
            pr: true
          run_phase: after_failure
        mariadb: '10.0'
      script:
        - python hello_world.py
        - cd python
        - pip install -r requirements.txt
